# Generated by Django 5.2.8 on 2025-11-08 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_table',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.department'),
            preserve_default=False,
        ),
    ]
